=== 1slander/bases-datos-avanzadas-gii/temas/tema-2/code/correo.dtd
<!ELEMENT correo (remitente, destinatario, asunto, mensaje)>
<!ATTLIST correo
    fecha CDATA #REQUIRED>

<!ELEMENT remitente EMPTY>
<!ATTLIST remitente
    nombre CDATA #REQUIRED
    email CDATA #REQUIRED>

<!ELEMENT destinatario EMPTY>
<!ATTLIST destinatario
    nombre CDATA #REQUIRED
    email CDATA #REQUIRED>

<!ELEMENT asunto (#PCDATA)>

<!ELEMENT mensaje (saludo, cuerpo, despedida, firma)>

<!ELEMENT saludo (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
<!ELEMENT despedida (#PCDATA)>

<!ELEMENT firma (nombre, departamento, universidad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>
<!ELEMENT universidad (#PCDATA)>

=== 1slander/bases-datos-avanzadas-gii/temas/tema-2/code/correo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE correo SYSTEM "correo.dtd">
<correo fecha="2025-10-27">
    <remitente nombre="Profesor de Bases de Datos" email="profesor@unir.edu"/>
    <destinatario nombre="Estudiante" email="alumno@unir.edu"/>
    <asunto>Bienvenida a la asignatura de Bases de Datos Avanzadas</asunto>

    <mensaje>
        <saludo>Estimado/a estudiante,</saludo>
        <cuerpo>
            Te damos la bienvenida a la asignatura Bases de Datos Avanzadas.
            En este curso veremos distintos tipos de bases de datos y aprenderemos
            a elegir la tecnología adecuada para cada caso real.
        </cuerpo>
        <despedida>¡Empezamos ya!</despedida>

        <firma>
            <nombre>Profesor del curso</nombre>
            <departamento>Escuela Superior de Ingeniería y Tecnología</departamento>
            <universidad>UNIR</universidad>
        </firma>
    </mensaje>
</correo>
